### ISSUE TITLE
Feature request: set http headers

### ISSUE THREAD

**Issue by fabien** [Janpot/next-rpc#14]
It would be interesting to be able to set http headers through the exported `config` object, like so:

```javascript
export const config = {
  rpc: true,
  headers: {
    'Cache-Control': 'max-age=60, s-maxage=60, stale-while-revalidate'
  }
}; 
```

**Comment by Janpot** [comment]
These wouldn't have any effect as `next-rpc` makes `POST` requests under the hood.

**Comment by fabien** [comment]
Ah, I hadn't looked into that. You are right, it would be useless in this case. How hard would it be to allow `GET` requests (optionally) and have such headers after all?

**Comment by Janpot** [comment]
There's several reasons to not use GET requests:
1. They can't have a body, therefore all data needs to be passed through headers/url, both of which have size limits. All functions of a rpc enabled file are multiplexed through 1 handler.
2. `next-rpc` enabled functions allow for both idempotent and non-idempotent behavior. That's why it uses POST requests under the hood. Changing that to GET will break that implicit contract that you can safely make non-idempotent requests with `next-rpc`. A browser may assume that it's safe to call such endpoint multiple times, or without confirmation. I prefer to not break that implicit contract for now.

`next-rpc` deliberately breaks out of the browser network management, that includes caching. It probably makes more sense to use a classic next.js API route if you need fine grained control over the transport layer. Rpc routes and classic API routes can happily live together in a project, one doesn't exclude the other.

Keep in mind that it's also possible to use your own caching layer in javascript. For instance libraries like `swr` can help with that.

**Comment by fabien** [comment]
I see what you mean, yes. I am already using `react-query` with `next-rpc`, for a moment I forget about this layer of caching as opposed to the HTTP layer in this case.
