### ISSUE TITLE
Allow wrapping rpc function

### ISSUE THREAD

**Issue by remorses** [Janpot/next-rpc#33]
Currently having the following code throws the error `rpc exports must be static functions` in the babel transform

```ts
export const config = { rpc: true }; // enable rpc on this API route


export const getName = wrapFunction(async function getName(code) {
  // ...
})
```

Wrapping the rpc function is useful to add error handling logic and tracing, the babel plugin should not error if the rpc function is a function wrapped by a function call

I can make a PR if you agree

**Comment by Janpot** [comment]
I have one problem with your proposal here, because the build errors for a reason. Currently, when you use typescript, there is the guarantee that if the project builds correctly, the runtime will correspond with the types. Imagine with this change, I define something like:
```ts
const wrapper = (method) => 'foo'
export const syncMethod = wrapper(async () => 'bar')
```
Now the compiler will happily allow that, but when I import it and run it I get
```ts
import { syncMethod } from '../api/rpc'
syncMethod();
// typescript type for result = 'string'
// runtime type on the server = 'string'
// runtime type on the client => Promise<'string'>
```
Now you can't rely on the types anymore. I specifically built this project to have a better typescript experience. I'm very specific about this in the [rules and limitations](https://www.npmjs.com/package/next-rpc#user-content-rules-and-limitations):

> Rpc routes are only **allowed to export async functions**. They also need to be statically analyzable as such.

Because I understand your pain, I'm currently considering adding a middleware API to achieve what you want. One possible signature this could have is

```tsx
type Method<P extends any[], R> = (...params: P) => Promise<R>;
type WrapMethod<P extends any[], R> = (method: Method<P, R>) => Method<P, R>;

interface Config {
  rpc: true;
  wrapMethod: WrapMethod<any[], any>;
}
```
This would allow you to write your example as

```tsx
export const config = { 
  rpc: true,
  wrapMethod: method => wrapFunction(method)
};

export const getName = async function getName(code) {
  // ...
}
```

**Comment by remorses** [comment]
Yes this would work too

**Comment by Janpot** [comment]
Added in v3.4.0: https://www.npmjs.com/package/next-rpc#middleware

**Comment by remorses** [comment]
Awesome!
